CREATE TABLE Users (
	UserID NUMERIC(10) NOT NULL AUTO_INCREMENT = 2023502400,
	CONSTRAINT Users_pk PRIMARY KEY (UserID),
	Username VARCHAR(25) NOT NULL,
	Password VARCHAR(25) NOT NULL,
	CONSTRAINT Users_un UNIQUE (Password),
	FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	JoinDate DATE NOT NULL,
	Email VARCHAR(50) NOT NULL
);

CREATE TABLE MetaData (
	TagID
	TagType
);

CREATE TABLE SurveyDetails (

);